[config]
default_to_workspace = false

[tasks.default]
clear = true
dependencies = ["run-my-redis"]

[tasks.run-my-redis]
cwd = "./my-redis"
command = "cargo"
args = ["run"]
watch = true

# [tasks.my-redis]
# cwd = "./my-redis"
# command = "cargo"
# args = ["run", "--example", "hello-redis"]
# watch = true
