[tasks.install-mini-redis-server]
install_crate = "mini-redis"
command = "mini-redis-server"

[tasks.run]
command = "cargo"
args = ["run"]
watch = true

[tasks.all]
run_task = [{ name = ["install-mini-redis-server", "run"], parallel = true }]

[tasks.hello-redis]
cwd = "my-redis"
command = "cargo"
args = ["run", "--example", "hello-redis"]

[tasks.hello-redis-all]
run_task = [{ name = ["run", "hello-redis"], parallel = true }]
